# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       shared-mime-info
Summary:    Shared MIME information database
Version:    1.0
Release:    1
Group:      System/Libraries
License:    GPL
URL:        http://freedesktop.org/Software/shared-mime-info
Source0:    http://people.freedesktop.org/~hadess/%{name}-%{version}.tar.xz
Source100:  shared-mime-info.yaml
Source101:  shared-mime-info-rpmlintrc
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  gawk
BuildRequires:  intltool
BuildRequires:  perl-XML-Parser >= 2.31-16


%description
This is the freedesktop.org shared MIME info database.

Many programs and desktops use the MIME system to represent the types of
files. Frequently, it is necessary to work out the correct MIME type for
a file. This is generally done by examining the file's name or contents,
and looking up the correct MIME type in a database.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
%description devel
Development files for %{name}



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-update-mimedb \
    --disable-nls

make

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
## remove these bogus files
%{__rm} -rf $RPM_BUILD_ROOT%{_datadir}/locale/*

%docs_package
# << install post


%post
# >> post
%{_bindir}/update-mime-database %{_datadir}/mime &> /dev/null || :
# << post




%files
%defattr(-,root,root,-)
%{_bindir}/*
%dir %{_datadir}/mime/
%{_datadir}/mime/packages
# >> files
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_datadir}/pkgconfig/*.pc
# << files devel


